import { Translations, Language } from '../types';

export const translations: Translations = {
  [Language.EN]: {
    loginAs: "Login as",
    // User Roles
    student: "Student",
    entrepreneur: "Entrepreneur",
    employer: "Employer",
    trainer: "Trainer",
    funder: "Funder",
    implementer: "Implementer",
    mentor: "Mentor",
    coach: "Coach",
    facilitator: "Facilitator",
    publisher: "Publisher",
    editor: "Editor",
    producer: "Producer",
    artist: "Artist",
    alumni: "Alumni",
    intern: "Intern",
    supervisor: "Supervisor",
    manager: "Manager",
    administrator: "Administrator",
    super_administrator: "Super Administrator",
    // Role Categories
    youth: "Youth",
    partner: "Partner",
    contributor_category: "Contributor",
    staff_category: "Staff",
    super_admin_category: "Super Administrator",

    login: "Login",
    dashboard: "Dashboard",
    courses: "Courses",
    jobs: "Jobs",
    ai_coach: "AI Coach",
    settings: "Settings",
    logout: "Logout",
    welcome: "Welcome",
    dashboard_title: "Your Dashboard",
    dashboard_subtitle: "Here's an overview of your activity.",
    my_courses: "My Courses",
    view_all_courses: "View All Courses",
    job_openings: "Job Openings",
    view_all_jobs: "View All Jobs",
    ai_coach_title: "AI Project & Strategy Coach",
    ai_coach_subtitle: "Get personalized advice, project ideas, and strategic guidance powered by AI.",
    ai_coach_prompt_placeholder: "Ask for a project idea, e.g., 'Suggest a marketing campaign for a new SaaS product.'",
    ai_coach_button: "Ask AI",
    ai_coach_thinking: "Thinking...",
    ai_coach_response_title: "AI Response",
    settings_title: "Settings",
    language: "Language",
    english: "English",
    french: "French",
    profile: "Profile",
    senegel_workflow_platform: "SENEGEL WorkFlow",
    course_duration: "Duration",
    course_progress: "Progress",
    job_posted: "Posted",
    job_type: "Type",
    job_location: "Location",
    projects: "Projects",
    project_management_title: "Intelligent Project Management",
    project_management_subtitle: "Create, manage, and track your projects with AI-powered assistance.",
    new_project: "New Project",
    create_project: "Create Project",
    project_title: "Project Title",
    project_description: "Project Description",
    due_date: "Due Date",
    team_members: "Team Members",
    status: "Status",
    not_started: "Not Started",
    in_progress: "In Progress",
    completed: "Completed",
    tasks: "Tasks",
    to_do: "To Do",
    done: "Done",
    generate_tasks_with_ai: "Generate Tasks with AI",
    gen_ai_lab: "Gen AI Lab",
    gen_ai_lab_title: "Generative AI Lab",
    gen_ai_lab_subtitle: "A space for AI-powered content creation. Generate images with Imagen or edit them with Nano Banana.",
    image_generator: "Image Generator",
    image_generator_subtitle: "Create stunning images from text descriptions. Powered by Imagen.",
    image_prompt_placeholder: "e.g., A vibrant market scene in Dakar with futuristic elements",
    generate_image: "Generate Image",
    generating: "Generating...",
    my_skills: "My Skills (Skill Passport)",
    skill_passport_subtitle: "This helps us match you with the right jobs and projects.",
    add_skill: "Add Skill",
    enter_skill: "Enter a skill...",
    my_job_postings: "My Job Postings",
    applicants: "Applicants",
    no_applicants: "No applicants yet.",
    view_applicants: "View Applicants",
    apply_now: "Apply Now",
    applied: "Applied",
    ai_smart_match: "AI Smart Match",
    top_candidate: "Top Candidate",
    my_projects: "My Projects",
    view_all_projects: "View All Projects",
    course_detail: "Course Detail",
    back_to_courses: "Back to Courses",
    modules: "Modules",
    lessons: "Lessons",
    start_learning: "Start Learning",
    continue_learning: "Continue Learning",
    course_management: "Course Management",
    course_management_subtitle: "Create, edit, and organize all courses on the platform.",
    add_new_course: "Add New Course",
    edit_course: "Edit Course",
    analytics: "Analytics",
    platform_analytics: "Platform Analytics",
    platform_analytics_subtitle: "Key metrics and insights into platform activity.",
    user_growth: "User Growth",
    enrollment_trends: "Enrollment Trends",
    job_application_funnel: "Job Application Funnel",
    view_talent_analytics: "View Talent Analytics",
    talent_analytics: "Talent Analytics",
    talent_analytics_subtitle: "Insights into the skills and potential of our user base.",
    back_to_analytics: "Back to Analytics",
    skill_gap_analysis: "Skill Gap Analysis",
    most_demanded_skills: "Most Demanded Skills (from Job Postings)",
    available_skills: "Top Available Skills (from User Passports)",
    talent_forecasting: "Talent Forecasting",
    talent_forecasting_subtitle: "Use AI to predict future talent needs and availability.",
    forecast_needs: "Forecast Needs",
    goals_okrs: "Goals (OKRs)",
    risk_management: "Risk Management",
    crm_sales: "CRM & Sales",
    knowledge_base: "Knowledge Base",
    goals_okrs_title: "Strategic Goal Alignment (OKRs)",
    goals_okrs_subtitle: "Define and track Objectives and Key Results for your projects.",
    select_project: "Select a Project",
    generate_okrs_with_ai: "Generate OKRs with AI",
    objective: "Objective",
    key_results: "Key Results",
    risk_management_tab: "Risk Management",
    identify_risks_with_ai: "Identify Risks with AI",
    likelihood: "Likelihood",
    impact: "Impact",
    mitigation_strategy: "Mitigation Strategy",
    high: "High",
    medium: "Medium",
    low: "Low",
    priority: "Priority",
    assignee: "Assignee",
    unassigned: "Unassigned",
    time_tracking: "Time Tracking",
    log_time: "Log Time",
    generate_status_report: "Generate Status Report",
    summarize_tasks: "Summarize Tasks",
    crm_title: "Customer Relationship Management",
    crm_subtitle: "Manage your contacts and sales pipeline.",
    draft_email_with_ai: "Draft Email with AI",
    knowledge_base_title: "Knowledge Base",
    knowledge_base_subtitle: "A central repository for your team's documents and knowledge.",
    create_doc_from_text: "Create New Document from Text",
    paste_text_here: "Paste your text here (e.g., meeting notes)...",
    summarize_and_create: "Summarize & Create",
    all_documents: "All Documents",
    create_new_job: "Create New Job",
    post_job: "Post Job",
    company_name: "Company Name",
    job_title: "Job Title",
    required_skills: "Required Skills",
    required_skills_placeholder: "e.g., React, Node.js, Marketing (comma-separated)",
    full_time: "Full-time",
    part_time: "Part-time",
    contract: "Contract",
    back_to_jobs: "Back to Jobs",
    user_management: "User Management",
    user_management_subtitle: "View and manage all platform users.",
    name: "Name",
    email: "Email",
    role: "Role",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    deactivate: "Deactivate",
    no_projects_found: "No projects found. Create one to get started!",
    no_courses_found: "No courses are available at the moment. Please check back later.",
    no_jobs_found: "No job openings found. Check back later or create a new one!",
    save: "Save",
    cancel: "Cancel",
    confirm_delete: "Confirm Delete",
    are_you_sure: "Are you sure?",
    confirm_delete_message: "This action cannot be undone. All associated data will be lost.",
    edit_project: "Edit Project",
    create_new_project: "Create New Project",
    delete_project: "Delete Project",
    instructor: "Instructor",
    course_icon: "Course Icon (FontAwesome)",
    add_module: "Add Module",
    add_lesson: "Add Lesson",
    edit_objective: "Edit Objective",
    create_objective: "Create Objective",
    delete_objective: "Delete Objective",
    add_key_result: "Add Key Result",
    target: "Target",
    unit: "Unit",
    current_value: "Current",
    create_contact: "Create Contact",
    edit_contact: "Edit Contact",
    delete_contact: "Delete Contact",
    contact_name: "Contact Name",
    contact_company: "Contact Company",
    contact_status: "Status",
    lead: "Lead",
    contacted: "Contacted",
    prospect: "Prospect",
    customer: "Customer",
    pipeline_view: "Pipeline",
    list_view: "List",
    work_email: 'Work Email',
    personal_email: 'Personal Email',
    office_phone: 'Office Phone',
    mobile_phone: 'Mobile Phone',
    whatsapp_number: 'WhatsApp Number',
    assign_role: "Assign Role",
    user_role: "User Role",
    ai_agent_title: 'SENEGEL WorkFlow AI',
    ai_agent_placeholder: 'Ask me anything...',
    ai_agent_send: 'Send',
    ai_agent_welcome_default: 'Hello! How can I help you today?',
    ai_agent_welcome_dashboard: 'Welcome to your dashboard! Ask me to find a section or summarize your activities.',
    ai_agent_welcome_projects: "In Projects, I can help you brainstorm tasks, identify risks, or draft project plans. What's on your mind?",
    ai_agent_welcome_goals_okrs: "Working on goals? I can help you define clear Objectives and Key Results (OKRs). Ask me how!",
    ai_agent_welcome_courses: "Ready to learn? Ask me to find a course on a specific topic or suggest a learning path.",
    ai_agent_welcome_jobs: "Looking for opportunities? I can help you find jobs that match your skills or give you interview tips.",
    ai_agent_welcome_knowledge_base: "This is your team's knowledge hub. Ask me to help you summarize notes or find a document.",
    ai_agent_welcome_ai_coach: "You're in the AI Coach section. While the coach gives detailed advice, I can help with quick questions about using this feature.",
    ai_agent_welcome_gen_ai_lab: "Welcome to the Gen AI Lab! Ask me for creative prompts for the image generator or other ideas.",
    ai_agent_welcome_crm_sales: "In the CRM, I can help you draft emails to contacts or suggest ways to manage your sales pipeline.",
    ai_agent_welcome_course_management: "Managing courses? I can help you structure modules, create lesson plans, or write course descriptions.",
    ai_agent_welcome_analytics: "Here you can see platform data. Ask me to explain a chart or what a certain metric means.",
    ai_agent_welcome_user_management: "From here you can manage all users. I can assist with understanding different roles and permissions.",
    ai_agent_welcome_settings: "In Settings, you can manage your profile. Ask me how to update your Skill Passport or change your language.",
    ai_agent_welcome_leave_management: "In Leave Management, you can request time off or manage team requests. Ask me how to submit a request.",
    my_time_logs: "My Time Logs",
    time_tracking_subtitle: "View, manage, and schedule your time across all activities.",
    total_time_logged: "Total Time Logged",
    duration_minutes: "Duration (minutes)",
    log_entry_for: "Log entry for",
    no_time_logs_found: "No time logs found.",
    time_logged_today: "Time Logged Today",
    time_logged_this_week: "Time Logged This Week",
    new_log_entry: "New Time Log Entry",
    select_type: "Select type...",
    select_course: "Select a Course",
    select_task_optional: "Select a Task (optional)",
    description: "Description",
    minutes: "minutes",
    view_time_logs: "View Time Logs",
    leave_management: "Leave Management",
    leave_management_subtitle: "Manage and view team leave requests and your own time off.",
    manage_leaves: "Manage Leaves",
    request_leave: "Request Leave",
    my_requests: "My Requests",
    team_requests: "Team Requests",
    start_date: "Start Date",
    end_date: "End Date",
    reason: "Reason",
    submit_request: "Submit Request",
    approve: "Approve",
    reject: "Reject",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    no_leave_requests: "No leave requests found.",
    team_availability: "Team Availability",
    upcoming_leaves: "Upcoming Leaves (Next 7 days)",
    no_upcoming_leaves: "No upcoming leaves.",
    signup_title: "Create Your Account",
    signup_subtitle: "Join the future of productivity.",
    full_name: "Full Name",
    phone_number: "Phone Number",
    password: "Password",
    confirm_password: "Confirm Password",
    signup_button: "Sign Up",
    signup_prompt: "Don't have an account? Sign up",
    login_prompt: "Already have an account? Login",
    passwords_do_not_match: "Passwords do not match.",
    email_in_use: "This email is already in use.",
    login_title: "Welcome Back!",
    login_subtitle: "Empowering your workflow, securely.",
    forgot_password: "Forgot Password?",
    need_help: "Need Help?",
    auth_ai_assistant_title: "Auth AI Assistant",
    password_strength: "Password Strength",
    strength_weak: "Weak",
    strength_medium: "Medium",
    strength_strong: "Strong",
    strength_very_strong: "Very Strong",
    auth_ai_prompt_roles: "What's the difference between the roles?",
    auth_ai_prompt_password: "I forgot my password. What do I do?",
    estimated_time_short: "Est. (h)",
    logged_time_short: "Logged (h)",
    finance: "Finance",
    finance_title: "Streamline Financial Operations & Optimize Profitability",
    finance_subtitle: "Rigorous financial management is the foundation of stability and growth. The Finance module centralizes all your financial operations, simplifying cash flow management and expense tracking.",
    view_finance: "View Finance",
    invoices: "Invoices",
    expenses: "Expenses",
    recurring: "Recurring",
    budgets: "Budgets",
    new_invoice: "New Invoice",
    new_expense: "New Expense",
    new_budget: "New Budget",
    total_revenue: "Total Revenue",
    total_expenses: "Total Expenses",
    net_income: "Net Income",
    total_outstanding_invoices: "Outstanding Invoices",
    total_due_expenses: "Due Expenses",
    average_payment_time: "Avg. Payment Time",
    days: "days",
    overdue: "Overdue",
    invoice_number: "Invoice #",
    client_name: "Client Name",
    amount: "Amount",
    draft: "Draft",
    sent: "Sent",
    paid: "Paid",
    partially_paid: "Partially Paid",
    paid_amount: "Paid Amount",
    unpaid: "Unpaid",
    category: "Category",
    date: "Date",
    create_invoice: "Create Invoice",
    edit_invoice: "Edit Invoice",
    create_expense: "Create Expense",
    edit_expense: "Edit Expense",
    delete_invoice: "Delete Invoice",
    delete_expense: "Delete Expense",
    receipt: "Receipt",
    upload_receipt: "Upload Receipt",
    download_receipt: "Download Receipt",
    view_receipt: "View Receipt",
    no_receipt_attached: "No receipt",
    payable_by: "Payable By",
    remove_receipt: "Remove",
    evidence_documents: "Evidence Documents",
    upload_evidence: "Upload Evidence",
    download_evidence: "Download Evidence",
    no_evidence_uploaded: "No evidence uploaded yet.",
    remove_evidence: "Remove",
    notifications: "Notifications",
    no_notifications: "No new notifications",
    reminder_settings: "Reminder Settings",
    remind_days_before: "Remind me (days before due)",
    invoice_due_reminder: "Invoice {invoiceNumber} is due on {dueDate}.",
    expense_due_reminder: "Expense for '{description}' is payable on {dueDate}.",
    mark_as_read: "Mark as read",
    clear_all: "Clear All",
    make_recurring: "Make this recurring?",
    frequency: "Frequency",
    monthly: "Monthly",
    quarterly: "Quarterly",
    annually: "Annually",
    end_date_optional: "End Date (Optional)",
    recurring_invoices: "Recurring Invoices",
    recurring_expenses: "Recurring Expenses",
    next_due_date: "Next Due Date",
    new_recurring_invoice: "New Recurring Invoice",
    new_recurring_expense: "New Recurring Expense",
    create_budget: "Create Budget",
    edit_budget: "Edit Budget",
    delete_budget: "Delete Budget",
    budget_title: "Budget Title",
    budget_type: "Budget Type",
    project_budget: "Project Budget",
    office_management: "Office Management",
    total_budget: "Total Budget",
    amount_spent: "Amount Spent",
    remaining: "Remaining",
    link_to_budget: "Link to Budget (Optional)",
    no_budget: "No Budget",
    view_details: "View Details",
    budget_lines: "Budget Lines",
    add_budget_line: "Add Budget Line",
    add_budget_item: "Add Item",
    item_description: "Item Description",
    planned_amount: "Planned",
    actual_spent: "Actual",
    calendar_and_meetings: "Calendar & Meetings",
    schedule_meeting: "Schedule Meeting",
    new_meeting: "New Meeting",
    edit_meeting: "Edit Meeting",
    delete_meeting: "Delete Meeting",
    meeting_title: "Meeting Title",
    start_time: "Start Time",
    end_time: "End Time",
    attendees: "Attendees",
    meeting_details: "Meeting Details",
    log_time_for_meeting: "Log Time for this Meeting",
    no_meetings_today: "No meetings scheduled for this day.",
    today: "Today",
    previous_week: "Previous Week",
    next_week: "Next Week",
    image_editing: "Image Editing",
    upload_image_to_edit: "Upload an image to get started",
    editing_prompt_placeholder: "e.g., Make this photo look like a watercolor painting",
    generate_edit: "Generate Edit",
    original_image: "Original Image",
    edited_image: "Edited Image",
    remove_image: "Remove Image",
    download_image: "Download Image",
    project_saved: "Project saved successfully.",
    invoice_saved: "Invoice saved successfully.",
    expense_saved: "Expense saved successfully.",
    contact_saved: "Contact saved successfully.",
    item_deleted: "Item deleted.",
    project_status_overview: "Project Status Overview",
    proactive_ai_suggestion_tasks: "Need help brainstorming tasks for your new project?",
    proactive_ai_suggestion_overdue: "I can help draft a reminder for your overdue invoices.",
  },
  [Language.FR]: {
    loginAs: "Se connecter en tant que",
    // User Roles
    student: "Étudiant",
    entrepreneur: "Entrepreneur",
    employer: "Employeur",
    trainer: "Formateur",
    funder: "Bailleur de fonds",
    implementer: "Implémenteur",
    mentor: "Mentor",
    coach: "Coach",
    facilitator: "Facilitateur",
    publisher: "Éditeur",
    editor: "Rédacteur",
    producer: "Producteur",
    artist: "Artiste",
    alumni: "Ancien élève",
    intern: "Stagiaire",
    supervisor: "Superviseur",
    manager: "Manager",
    administrator: "Administrateur",
    super_administrator: "Super Administrateur",
    // Role Categories
    youth: "Jeunesse",
    partner: "Partenaire",
    contributor_category: "Contributeur",
    staff_category: "Personnel",
    super_admin_category: "Super Administrateur",

    login: "Connexion",
    dashboard: "Tableau de Bord",
    courses: "Formations",
    jobs: "Emplois",
    ai_coach: "Coach IA",
    settings: "Paramètres",
    logout: "Déconnexion",
    welcome: "Bienvenue",
    dashboard_title: "Votre Tableau de Bord",
    dashboard_subtitle: "Voici un aperçu de votre activité.",
    my_courses: "Mes Formations",
    view_all_courses: "Voir Toutes les Formations",
    job_openings: "Offres d'Emploi",
    view_all_jobs: "Voir Tous les Emplois",
    ai_coach_title: "Coach IA de Projet & Stratégie",
    ai_coach_subtitle: "Obtenez des conseils personnalisés, des idées de projets et une orientation stratégique grâce à l'IA.",
    ai_coach_prompt_placeholder: "Demandez une idée de projet, ex: 'Suggérez une campagne marketing pour un nouveau produit SaaS.'",
    ai_coach_button: "Demander à l'IA",
    ai_coach_thinking: "Réflexion...",
    ai_coach_response_title: "Réponse de l'IA",
    settings_title: "Paramètres",
    language: "Langue",
    english: "Anglais",
    french: "Français",
    profile: "Profil",
    senegel_workflow_platform: "SENEGEL WorkFlow",
    course_duration: "Durée",
    course_progress: "Progression",
    job_posted: "Publié le",
    job_type: "Type",
    job_location: "Lieu",
    projects: "Projets",
    project_management_title: "Gestion de Projets Intelligente",
    project_management_subtitle: "Créez, gérez et suivez vos projets avec l'assistance de l'IA.",
    new_project: "Nouveau Projet",
    create_project: "Créer le Projet",
    project_title: "Titre du Projet",
    project_description: "Description du Projet",
    due_date: "Date d'Échéance",
    team_members: "Membres de l'équipe",
    status: "Statut",
    not_started: "Non commencé",
    in_progress: "En cours",
    completed: "Terminé",
    tasks: "Tâches",
    to_do: "À Faire",
    done: "Terminé",
    generate_tasks_with_ai: "Générer les Tâches avec l'IA",
    gen_ai_lab: "Labo IA Gén.",
    gen_ai_lab_title: "Laboratoire d'IA Générative",
    gen_ai_lab_subtitle: "Un espace pour la création de contenu par l'IA. Générez des images avec Imagen ou modifiez-les avec Nano Banana.",
    image_generator: "Générateur d'Images",
    image_generator_subtitle: "Créez des images époustouflantes à partir de descriptions textuelles. Propulsé par Imagen.",
    image_prompt_placeholder: "ex: Une scène de marché animée à Dakar avec des éléments futuristes",
    generate_image: "Générer l'Image",
    generating: "Génération...",
    my_skills: "Mes Compétences (Passeport de Compétences)",
    skill_passport_subtitle: "Cela nous aide à vous mettre en relation avec les bons emplois et projets.",
    add_skill: "Ajouter Compétence",
    enter_skill: "Entrez une compétence...",
    my_job_postings: "Mes Offres d'Emploi",
    applicants: "Candidats",
    no_applicants: "Aucun candidat pour le moment.",
    view_applicants: "Voir les Candidats",
    apply_now: "Postuler",
    applied: "Postulé",
    ai_smart_match: "Match Intelligent IA",
    top_candidate: "Meilleur Candidat",
    my_projects: "Mes Projets",
    view_all_projects: "Voir Tous les Projets",
    course_detail: "Détail de la Formation",
    back_to_courses: "Retour aux Formations",
    modules: "Modules",
    lessons: "Leçons",
    start_learning: "Commencer l'Apprentissage",
    continue_learning: "Continuer l'Apprentissage",
    course_management: "Gestion des Formations",
    course_management_subtitle: "Créez, modifiez et organisez toutes les formations de la plateforme.",
    add_new_course: "Ajouter une Formation",
    edit_course: "Modifier la Formation",
    analytics: "Analytique",
    platform_analytics: "Analytiques de la Plateforme",
    platform_analytics_subtitle: "Métriques clés et aperçus de l'activité de la plateforme.",
    user_growth: "Croissance des Utilisateurs",
    enrollment_trends: "Tendances d'Inscription",
    job_application_funnel: "Entonnoir de Candidature",
    view_talent_analytics: "Voir l'Analyse des Talents",
    talent_analytics: "Analyse des Talents",
    talent_analytics_subtitle: "Aperçu des compétences et du potentiel de notre base d'utilisateurs.",
    back_to_analytics: "Retour aux Analytiques",
    skill_gap_analysis: "Analyse des Écarts de Compétences",
    most_demanded_skills: "Compétences les Plus Demandées (des offres d'emploi)",
    available_skills: "Top Compétences Disponibles (des passeports utilisateurs)",
    talent_forecasting: "Prévision des Talents",
    talent_forecasting_subtitle: "Utilisez l'IA pour prédire les futurs besoins et la disponibilité des talents.",
    forecast_needs: "Prévoir les Besoins",
    goals_okrs: "Objectifs (OKRs)",
    risk_management: "Gestion des Risques",
    crm_sales: "CRM & Ventes",
    knowledge_base: "Base de Connaissances",
    goals_okrs_title: "Alignement Stratégique (OKRs)",
    goals_okrs_subtitle: "Définissez et suivez les Objectifs et Résultats Clés pour vos projets.",
    select_project: "Sélectionner un Projet",
    generate_okrs_with_ai: "Générer les OKRs avec l'IA",
    objective: "Objectif",
    key_results: "Résultats Clés",
    risk_management_tab: "Gestion des Risques",
    identify_risks_with_ai: "Identifier les Risques avec l'IA",
    likelihood: "Probabilité",
    impact: "Impact",
    mitigation_strategy: "Stratégie d'Atténuation",
    high: "Élevé",
    medium: "Moyen",
    low: "Faible",
    priority: "Priorité",
    assignee: "Assigné à",
    unassigned: "Non assigné",
    time_tracking: "Suivi du Temps",
    log_time: "Pointer",
    generate_status_report: "Générer un Rapport d'Avancement",
    summarize_tasks: "Résumer les Tâches",
    crm_title: "Gestion de la Relation Client",
    crm_subtitle: "Gérez vos contacts et votre pipeline de ventes.",
    draft_email_with_ai: "Rédiger un E-mail avec l'IA",
    knowledge_base_title: "Base de Connaissances",
    knowledge_base_subtitle: "Un référentiel central pour les documents et les connaissances de votre équipe.",
    create_doc_from_text: "Créer un Document à Partir d'un Texte",
    paste_text_here: "Collez votre texte ici (ex: notes de réunion)...",
    summarize_and_create: "Résumer & Créer",
    all_documents: "Tous les Documents",
    create_new_job: "Créer une Offre d'Emploi",
    post_job: "Publier l'Offre",
    company_name: "Nom de l'Entreprise",
    job_title: "Titre du Poste",
    required_skills: "Compétences Requises",
    required_skills_placeholder: "ex: React, Node.js, Marketing (séparées par des virgules)",
    full_time: "Temps plein",
    part_time: "Temps partiel",
    contract: "Contrat",
    back_to_jobs: "Retour aux Emplois",
    user_management: "Gestion des Utilisateurs",
    user_management_subtitle: "Voir et gérer tous les utilisateurs de la plateforme.",
    name: "Nom",
    email: "E-mail",
    role: "Rôle",
    actions: "Actions",
    edit: "Modifier",
    delete: "Supprimer",
    deactivate: "Désactiver",
    no_projects_found: "Aucun projet trouvé. Créez-en un pour commencer !",
    no_courses_found: "Aucune formation n'est disponible pour le moment. Veuillez revenir plus tard.",
    no_jobs_found: "Aucune offre d'emploi trouvée. Revenez plus tard ou créez-en une nouvelle !",
    save: "Enregistrer",
    cancel: "Annuler",
    confirm_delete: "Confirmer la Suppression",
    are_you_sure: "Êtes-vous sûr(e) ?",
    confirm_delete_message: "Cette action est irréversible. Toutes les données associées seront perdues.",
    edit_project: "Modifier le Projet",
    create_new_project: "Créer un Nouveau Projet",
    delete_project: "Supprimer le Projet",
    instructor: "Instructeur",
    course_icon: "Icône de la formation (FontAwesome)",
    add_module: "Ajouter un Module",
    add_lesson: "Ajouter une Leçon",
    edit_objective: "Modifier l'Objectif",
    create_objective: "Créer un Objectif",
    delete_objective: "Supprimer l'Objectif",
    add_key_result: "Ajouter un Résultat Clé",
    target: "Cible",
    unit: "Unité",
    current_value: "Actuel",
    create_contact: "Créer un Contact",
    edit_contact: "Modifier le Contact",
    delete_contact: "Supprimer le Contact",
    contact_name: "Nom du Contact",
    contact_company: "Société du Contact",
    contact_status: "Statut",
    lead: "Piste",
    contacted: "Contacté",
    prospect: "Prospect",
    customer: "Client",
    pipeline_view: "Pipeline",
    list_view: "Liste",
    work_email: 'E-mail Professionnel',
    personal_email: 'E-mail Personnel',
    office_phone: 'Téléphone Bureau',
    mobile_phone: 'Téléphone Portable',
    whatsapp_number: 'Numéro WhatsApp',
    assign_role: "Attribuer un Rôle",
    user_role: "Rôle de l'utilisateur",
    ai_agent_title: 'SENEGEL WorkFlow IA',
    ai_agent_placeholder: 'Posez-moi une question...',
    ai_agent_send: 'Envoyer',
    ai_agent_welcome_default: 'Bonjour! Comment puis-je vous aider aujourd\'hui ?',
    ai_agent_welcome_dashboard: 'Bienvenue sur votre tableau de bord ! Demandez-moi de trouver une section ou de résumer vos activités.',
    ai_agent_welcome_projects: "Dans Projets, je peux vous aider à imaginer des tâches, identifier des risques ou rédiger des plans. Qu'avez-vous en tête ?",
    ai_agent_welcome_goals_okrs: "Vous travaillez sur des objectifs ? Je peux vous aider à définir des Objectifs et Résultats Clés (OKRs). Demandez-moi comment !",
    ai_agent_welcome_courses: "Prêt à apprendre ? Demandez-moi de trouver une formation ou de suggérer un parcours d'apprentissage.",
    ai_agent_welcome_jobs: "En quête d'opportunités ? Je peux vous aider à trouver des emplois ou vous donner des conseils d'entretien.",
    ai_agent_welcome_knowledge_base: "Ceci est la base de connaissances de votre équipe. Demandez-moi de résumer des notes ou de trouver un document.",
    ai_agent_welcome_ai_coach: "Vous êtes dans le Coach IA. Tandis qu'il donne des conseils détaillés, je peux répondre à des questions rapides.",
    ai_agent_welcome_gen_ai_lab: "Bienvenue au Labo IA Gén. ! Demandez-moi des prompts créatifs pour le générateur d'images.",
    ai_agent_welcome_crm_sales: "Dans le CRM, je peux vous aider à rédiger des e-mails ou suggérer des façons de gérer votre pipeline de ventes.",
    ai_agent_welcome_course_management: "Vous gérez des formations ? Je peux vous aider à structurer des modules ou créer des plans de cours.",
    ai_agent_welcome_analytics: "Ici, vous voyez les données de la plateforme. Demandez-moi d'expliquer un graphique.",
    ai_agent_welcome_user_management: "D'ici, vous pouvez gérer les utilisateurs. Je peux vous aider à comprendre les rôles et permissions.",
    ai_agent_welcome_settings: "Dans les Paramètres, gérez votre profil. Demandez-moi comment mettre à jour votre Passeport de Compétences.",
    ai_agent_welcome_leave_management: "Dans la Gestion des Congés, vous pouvez demander des congés ou gérer les demandes de l'équipe. Demandez-moi comment faire.",
    my_time_logs: "Mes Pointages",
    time_tracking_subtitle: "Consultez, gérez et planifiez votre temps pour toutes les activités.",
    total_time_logged: "Temps Total Pointé",
    duration_minutes: "Durée (minutes)",
    log_entry_for: "Pointage pour",
    no_time_logs_found: "Aucun pointage trouvé.",
    time_logged_today: "Temps Pointé Aujourd'hui",
    time_logged_this_week: "Temps Pointé Cette Semaine",
    new_log_entry: "Nouveau Pointage",
    select_type: "Sélectionner le type...",
    select_course: "Sélectionner une Formation",
    select_task_optional: "Sélectionner une Tâche (optionnel)",
    description: "Description",
    minutes: "minutes",
    view_time_logs: "Voir les Pointages",
    leave_management: "Gestion des Congés",
    leave_management_subtitle: "Gérez et consultez les demandes de congés de l'équipe et vos propres congés.",
    manage_leaves: "Gérer les Congés",
    request_leave: "Demander un Congé",
    my_requests: "Mes Demandes",
    team_requests: "Demandes de l'Équipe",
    start_date: "Date de Début",
    end_date: "Date de Fin",
    reason: "Raison",
    submit_request: "Envoyer la Demande",
    approve: "Approuver",
    reject: "Rejeter",
    pending: "En attente",
    approved: "Approuvé",
    rejected: "Rejeté",
    no_leave_requests: "Aucune demande de congé trouvée.",
    team_availability: "Disponibilité de l'Équipe",
    upcoming_leaves: "Congés à Venir (7 prochains jours)",
    no_upcoming_leaves: "Aucun congé à venir.",
    signup_title: "Créez Votre Compte",
    signup_subtitle: "Rejoignez le futur de la productivité.",
    full_name: "Nom Complet",
    phone_number: "Numéro de Téléphone",
    password: "Mot de Passe",
    confirm_password: "Confirmer le Mot de Passe",
    signup_button: "S'inscrire",
    signup_prompt: "Vous n'avez pas de compte ? Inscrivez-vous",
    login_prompt: "Vous avez déjà un compte ? Connexion",
    passwords_do_not_match: "Les mots de passe ne correspondent pas.",
    email_in_use: "Cet e-mail est déjà utilisé.",
    login_title: "Content de vous revoir !",
    login_subtitle: "Optimisez votre flux de travail, en toute sécurité.",
    forgot_password: "Mot de passe oublié ?",
    need_help: "Besoin d'aide ?",
    auth_ai_assistant_title: "Assistant IA d'Authentification",
    password_strength: "Force du mot de passe",
    strength_weak: "Faible",
    strength_medium: "Moyen",
    strength_strong: "Fort",
    strength_very_strong: "Très fort",
    auth_ai_prompt_roles: "Quelle est la différence entre les rôles ?",
    auth_ai_prompt_password: "J'ai oublié mon mot de passe. Que faire ?",
    estimated_time_short: "Est. (h)",
    logged_time_short: "Pointé (h)",
    finance: "Finance",
    finance_title: "Rationaliser les Opérations Financières et Optimiser la Rentabilité",
    finance_subtitle: "Une gestion financière rigoureuse est le fondement de la stabilité et de la croissance. Le module Finance de SENEGEL centralise toutes vos opérations financières, simplifiant la gestion des flux de trésorerie et le suivi des dépenses.",
    view_finance: "Voir les Finances",
    invoices: "Factures",
    expenses: "Dépenses",
    recurring: "Récurrent",
    budgets: "Budgets",
    new_invoice: "Nouvelle Facture",
    new_expense: "Nouvelle Dépense",
    new_budget: "Nouveau Budget",
    total_revenue: "Revenu Total",
    total_expenses: "Dépenses Totales",
    net_income: "Revenu Net",
    total_outstanding_invoices: "Factures Impayées",
    total_due_expenses: "Dépenses Dues",
    average_payment_time: "Temps Paiement Moy.",
    days: "jours",
    overdue: "En Retard",
    invoice_number: "Facture n°",
    client_name: "Nom du Client",
    amount: "Montant",
    draft: "Brouillon",
    sent: "Envoyée",
    paid: "Payée",
    partially_paid: "Partiellement Payée",
    paid_amount: "Montant Payé",
    unpaid: "Impayée",
    category: "Catégorie",
    date: "Date",
    create_invoice: "Créer une Facture",
    edit_invoice: "Modifier la Facture",
    create_expense: "Créer une Dépense",
    edit_expense: "Modifier la Dépense",
    delete_invoice: "Supprimer la Facture",
    delete_expense: "Supprimer la Dépense",
    receipt: "Reçu",
    upload_receipt: "Télécharger un reçu",
    download_receipt: "Télécharger le reçu",
    view_receipt: "Voir le reçu",
    no_receipt_attached: "Aucun reçu",
    payable_by: "Payable avant le",
    remove_receipt: "Retirer",
    evidence_documents: "Documents de Preuve",
    upload_evidence: "Télécharger une Preuve",
    download_evidence: "Télécharger la Preuve",
    no_evidence_uploaded: "Aucune preuve téléchargée.",
    remove_evidence: "Retirer",
    notifications: "Notifications",
    no_notifications: "Aucune nouvelle notification",
    reminder_settings: "Paramètres des rappels",
    remind_days_before: "Me rappeler (jours avant l'échéance)",
    invoice_due_reminder: "La facture {invoiceNumber} est due le {dueDate}.",
    expense_due_reminder: "La dépense pour '{description}' est payable le {dueDate}.",
    mark_as_read: "Marquer comme lu",
    clear_all: "Tout effacer",
    make_recurring: "Rendre récurrent ?",
    frequency: "Fréquence",
    monthly: "Mensuel",
    quarterly: "Trimestriel",
    annually: "Annuel",
    end_date_optional: "Date de fin (Optionnel)",
    recurring_invoices: "Factures Récurrentes",
    recurring_expenses: "Dépenses Récurrentes",
    next_due_date: "Prochaine Échéance",
    new_recurring_invoice: "Nouvelle Facture Récurrente",
    new_recurring_expense: "Nouvelle Dépense Récurrente",
    create_budget: "Créer un Budget",
    edit_budget: "Modifier le Budget",
    delete_budget: "Supprimer le Budget",
    budget_title: "Titre du Budget",
    budget_type: "Type de Budget",
    project_budget: "Budget de Projet",
    office_management: "Gestion de Bureau",
    total_budget: "Budget Total",
    amount_spent: "Montant Dépensé",
    remaining: "Restant",
    link_to_budget: "Lier à un Budget (Optionnel)",
    no_budget: "Pas de Budget",
    view_details: "Voir les détails",
    budget_lines: "Lignes Budgétaires",
    add_budget_line: "Ajouter une Ligne",
    add_budget_item: "Ajouter un Poste",
    item_description: "Description du Poste",
    planned_amount: "Prévu",
    actual_spent: "Dépensé",
    calendar_and_meetings: "Calendrier & Réunions",
    schedule_meeting: "Planifier une réunion",
    new_meeting: "Nouvelle Réunion",
    edit_meeting: "Modifier la Réunion",
    delete_meeting: "Supprimer la Réunion",
    meeting_title: "Titre de la Réunion",
    start_time: "Heure de début",
    end_time: "Heure de fin",
    attendees: "Participants",
    meeting_details: "Détails de la Réunion",
    log_time_for_meeting: "Pointer pour cette réunion",
    no_meetings_today: "Aucune réunion prévue pour ce jour.",
    today: "Aujourd'hui",
    previous_week: "Semaine Précédente",
    next_week: "Semaine Suivante",
    image_editing: "Édition d'Image",
    upload_image_to_edit: "Téléchargez une image pour commencer",
    editing_prompt_placeholder: "ex: Donner à cette photo l'aspect d'une peinture à l'aquarelle",
    generate_edit: "Générer la Modification",
    original_image: "Image Originale",
    edited_image: "Image Modifiée",
    remove_image: "Retirer l'Image",
    download_image: "Télécharger l'Image",
    project_saved: "Projet enregistré avec succès.",
    invoice_saved: "Facture enregistrée avec succès.",
    expense_saved: "Dépense enregistrée avec succès.",
    contact_saved: "Contact enregistré avec succès.",
    item_deleted: "Élément supprimé.",
    project_status_overview: "Aperçu du Statut des Projets",
    proactive_ai_suggestion_tasks: "Besoin d'aide pour trouver des tâches pour votre nouveau projet ?",
    proactive_ai_suggestion_overdue: "Je peux aider à rédiger un rappel pour vos factures en retard.",
  },
};